export const EVENT_REPORT_SUCCESS = 'EVENT_REPORT_SUCCESS';
export const EVENT_REPORT_FAIL = 'EVENT_REPORT_FAIL';
export const EVENT_REPORT_START = 'EVENT_REPORT_START';
export const EVENT_REPORT_DELETE = 'EVENT_REPORT_DELETE';

export const FETCH_REPORTS_START = 'FETCH_REPORTS_START'
export const FETCH_REPORTS_SUCCESS = 'FETCH_REPORTS_SUCCESS'
export const FETCH_REPORTS_FAIL = 'FETCH_REPORTS_FAIL'

export const ADD_GARD_SUCCESS = 'ADD_GARD_SUCCESS';
export const ADD_GARD_FAIL = 'ADD_GARD_FAIL';
export const ADD_GARD_START = 'ADD_GARD_START';

export const FETCH_GARDS = 'FETCH_GARDS';
export const FETCH_GARDS_START = 'FETCH_GARDS_START';
export const FETCH_GARDS_FAIL = 'FETCH_GARDS_FAIL';
export const FETCH_GARDS_SUCCES = 'FETCH_GARDS_SUCCES';

export const ADD_PRESSURE_SUCCESS = 'ADD_PRESSURE_SUCCESS';
export const ADD_PRESSURE_FAIL = 'ADD_PRESSURE_FAIL';
export const ADD_PRESSURE_START = 'ADD_PRESSURE_START';

export const FETCH_PRESSURE = 'FETCH_PRESSURE';
export const FETCH_PRESSURE_START = 'FETCH_PRESSURE_START';
export const FETCH_PRESSURE_FAIL = 'FETCH_PRESSURE_FAIL';
export const FETCH_PRESSURE_SUCCES = 'FETCH_PRESSURE_SUCCES';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';


