export const EVENT_REPORT_SUCCESS = 'EVENT_REPORT_SUCCESS';
export const EVENT_REPORT_FAIL = 'EVENT_REPORT_FAIL';
export const EVENT_REPORT_START = 'EVENT_REPORT_START';

export const FETCH_REPORTS_START = 'FETCH_REPORTS_START'
export const FETCH_REPORTS_SUCCESS = 'FETCH_REPORTS_SUCCESS'
export const FETCH_REPORTS_FAIL = 'FETCH_REPORTS_FAIL'

export const ADD_GARD_SUCCESS = 'ADD_GARD_SUCCESS';
export const ADD_GARD_FAIL = 'REMOVE_EVENT_REPORT_FAIL';
export const ADD_GARD_START = 'EVENT_REPORT_START';

export const FETCH_GARDS = 'FETCH_GARDS';
export const FETCH_GARDS_START = 'FETCH_GARDS_START';
export const FETCH_GARDS_FAIL = 'FETCH_GARDS_FAIL';
export const FETCH_GARDS_SUCCES = 'FETCH_GARDS_SUCCES';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
